CREATE TABLE ALUNO
(RM	  INT			 NULL,
 NOME VARCHAR(40)	 NOT NULL,
 RG VARCHAR(20)		 NOT NULL,
 CPF VARCHAR(19)	 NOT NULL)


ALTER PROCEDURE PROC01 @RM INT, @NOME VARCHAR(40), @RG VARCHAR(20), @CPF VARCHAR(19)
AS
BEGIN
	SET NOCOUNT ON
	
	IF (@RM IS NULL)
	BEGIN
		DECLARE @RMNOVO INT
		SELECT @RMNOVO = ISNULL(MAX(RM),0)+1 FROM ALUNO
			IF  (NOT EXISTS (SELECT @RG, @CPF 
								FROM ALUNO 
								WHERE RG = @RG OR CPF = @CPF))
				
					INSERT INTO ALUNO (RM, NOME, RG, CPF)
					VALUES (@RMNOVO, @NOME, @RG, @CPF)
				
	END
	IF(@NOME IS NULL AND @RG IS NULL AND @CPF IS NULL)
	BEGIN
		DELETE FROM ALUNO
		WHERE RM = @RM 
	END
	IF(@NOME IS NOT NULL OR @RG IS NOT NULL OR @CPF IS NOT NULL)
	BEGIN
		UPDATE ALUNO 
		SET RM = @RM, NOME = @NOME, RG = @RG, CPF = @CPF
		WHERE RM = @RM 
	END  
	SET NOCOUNT OFF
END

EXEC PROC01 1, 'DIEGO', '157781', NULL 
EXEC PROC01 NULL, 'CARLOS', '157781', NULL
EXEC PROC01 NULL, 'ARLINDO', '124575', '12315647'
EXEC PROC01 NULL, 'ANDERSON', '11224575', '12315647'



SELECT * FROM ALUNO

